Update Store & User Models
wyncode/C40_Final_Andrew_Jespson_Peter_Trisha pull request #9
Opened 2020-12-20 09:21 UTC by revelted

2020-12-20 12:32 UTC, leopolicastro requested changes

2020-12-20 12:32 UTC, leopolicastro commented on server/db/models/store.js
> +      },
street city and state should be its own attribute

2020-12-20 12:32 UTC, leopolicastro commented on server/db/models/store.js
> +    availabilityCalender: {
typo here

2020-12-20 12:32 UTC, leopolicastro commented on server/db/models/store.js
> +};
this doesn't seem to be doing anything.

2020-12-21 01:47 UTC, JespsonSTP commented on server/db/models/store.js
> +      },
this is so it can be easier when using geolocation api. we can get all that information in attribute

2020-12-22 00:25 UTC, merged